name: "Public Nightly Release"
on:
  push:
    branches: ["main"]

jobs:
  release-nightly:
    name: Release Nightly build to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Build and push the image to Docker Hub
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE_NAME }}
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to Docker Hub 
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
          echo "Pushing image to Docker Hub..."
          docker push $DOCKER_IMAGE:$IMAGE_TAG
